"""empty message

Revision ID: 95ef5445d042
Revises: e7d595b5c9c3
Create Date: 2026-07-27 22:16:50.324195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ef5445d042'
down_revision = 'e7d595b5c9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employee_company_email'), type_='unique')
        batch_op.drop_constraint(batch_op.f('employee_company_id_fkey'), type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('employee_company_id_fkey'), 'company', ['company_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_employee_company_email'), ['company_id', 'email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
